# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd9a94b6634252d575c14a5a92ae47fb4e585593eb60b6b3b1e8515b512bc850aa2491721234b485d8000c5363bd416e95168dc39f7ac9821e5f60abf9493dd

test:
  secret_key_base: d8013418c1fc3375ac22aa944df71e91d0580b542d3a960c686460a891cf33569913433738b1720324a6021696dbf855a129fc035c41435a48f77de61f0e7f25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
